name: "Build and push docker image"
description: "Build and push docker image"
inputs:
  build-version:
    description: "Image tag for the docker image"
    required: true
  github-token:
    description: "Token to use when signing into ghcr.io"
    required: true
  project_id:
    required: true
    description: "NAIS project id"
  identity_provider:
    required: true
    description: "NAIS identity provider"
  namespace:
    required: false
    description: "NAV team"
    default: "teamforeldrepenger"
  push-image:
    required: false
    description: "Push the docker image to gchr.io (true|false)"
    default: "false"
  bake-action:
    required: false
    description: "Use docker bake action to build and push"
    default: "false"
  bake-platform:
    required: false
    description: Platform to target
    default: ""
  bake-cache-tag:
    required: false
    description: Tag for cache image
    default: ""
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # ratchet:docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # ratchet:docker/setup-buildx-action@v2
    - name: NAIS login
      if: inputs.bake-action == 'false'
      uses: nais/login@104bca34b70d1d00fe837bcd0689633978eca744 # ratchet:nais/login@v0
      id: login
      with:
        project_id: ${{ inputs.project_id }}
        identity_provider: ${{ inputs.identity_provider }}
        team: ${{ inputs.namespace }}
    - name: Docker meta
      if: inputs.bake-action == 'false'
      uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # ratchet:docker/metadata-action@v4
      id: meta
      with:
        images: |
          ${{ steps.login.outputs.registry }}/${{ github.repository }}
          ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=${{ inputs.build-version }}
        flavor: |
          latest=true
    - name: Bygg og push docker image
      if: inputs.bake-action == 'false'
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # ratchet:docker/build-push-action@v4
      id: build_push
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        pull: true
        push: ${{ inputs.push-image == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Generate SBOM, attest and sign image
      if: (inputs.push-image == 'true' && inputs.bake-action == 'false')
      uses: nais/attest-sign@b21f2f03bcfa1e51f39b52690732017787c4d03f # ratchet:nais/attest-sign@v1.0.0
      with:
        image_ref: ${{ steps.login.outputs.registry }}/${{ github.repository }}@${{ steps.build_push.outputs.digest }}
    - name: Build and push with bake
      if: inputs.bake-action == 'true'
      uses: docker/bake-action@ad0d2a9712378c502a7d5c590deb0d7a02d2a61d # ratchet:docker/bake-action@v3.0.1
      env:
        TAG: ${{ inputs.bake-platform }}-${{ github.sha }}
        CACHE_TAG: ${{ inputs.bake-cache-tag }}
      with:
        push: ${{ inputs.push-image == 'true' }}
        set: |
          *.platform=linux/${{ inputs.bake-platform }}
