name: "Build and push docker images"
description: "Build and push docker images using docker bake"
inputs:
  build-version:
    description: "Image tag for the docker image"
    required: true
  project_id:
    required: true
    description: "NAIS project id"
  identity_provider:
    required: true
    description: "NAIS identity provider"
  namespace:
    required: false
    description: "NAV team"
    default: "teamforeldrepenger"
  push-image:
    required: false
    description: "Push the docker image (true|false)"
    default: "false"
  bake-platform:
    required: false
    description: Platform to target
    default: "linux/amd64,linux/arm64"
  bake-target:
    required: true
    description: Bake target
  github-token:
    description: "Token to use when signing into ghcr.io for cacheing purposes"
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Packages Docker Registry # Brukes ifm lagring og henting av cache
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # ratchet:docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # ratchet:docker/setup-buildx-action@v2
    - name: NAIS login
      uses: nais/login@104bca34b70d1d00fe837bcd0689633978eca744 # ratchet:nais/login@v0
      id: login
      with:
        project_id: ${{ inputs.project_id }}
        identity_provider: ${{ inputs.identity_provider }}
        team: ${{ inputs.namespace }}
    - name: Docker meta
      uses: docker/metadata-action@31cebacef4805868f9ce9a0cb03ee36c32df2ac4 # ratchet:docker/metadata-action@v4
      id: meta
      with:
        images: ${{ steps.login.outputs.registry }}/${{ github.repository }}/${{ inputs.bake-target }}
        tags: |
          type=raw,value=${{ inputs.build-version }}
          # set latest tag for default branch (master)
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Generate cache tags
      shell: bash
      id: generate-cache-tags
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: |
        GITHUB_REF_NAME=${GITHUB_REF_NAME//\//_}
        echo "cache-tag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
    # - name: Generate SBOM, attest and sign image
    #   if: inputs.push-image == 'true'
    #   uses: nais/attest-sign@53b7a991bd5b5a9903cc8434e584345980a31032 # ratchet:nais/attest-sign@v1.1.0
    #   with:
    #     image_ref: ${{ steps.login.outputs.registry }}/${{ github.repository }}/${{ inputs.bake-target }}@${{ steps.build_push.outputs.digest }}

    - name: Build and push with bake
      uses: docker/bake-action@849707117b03d39aba7924c50a10376a69e88d7d # ratchet:docker/bake-action@v4.1.0
      env:
        CACHE_TAG: ${{ steps.generate-cache-tags.outputs.cache-tag }}
      with:
        targets: ${{ inputs.bake-target }}
        push: ${{ inputs.push-image }}
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        set: |
          *.platform=${{ inputs.bake-platform }}
