name: 'Maven install'
description: 'Maven install'
inputs:
  t-2c:
    description: 'Thread config to use'
    required: false
    default: ''
  skip-tests:
    description: 'Skip tests'
    required: false
    default: 'false'
outputs:
  build-version:
    description: "Build version"
    value: ${{ steps.generate-build-version.outputs.build-version }}
runs:
  using: "composite"
  steps:
    - name: Generate build version
      id: generate-build-version
      shell: bash
      run: echo "build-version=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Print build version
      shell: bash
      run: echo "Generated build-version is ${{ steps.generate-build-version.outputs.build-version }}"

    - name: Build artifacts
      shell: bash
      run: |
        echo "Building artifacts ${{ steps.generate-build-version.outputs.build-version }}"
        mvn versions:set -DnewVersion="${{ steps.generate-build-version.outputs.build-version }}" -s settings.xml -q -e -B
        mvn install -s settings.xml ${{ inputs.t-2c }} -q -e -B -Psonar ${{ (inputs.skip-tests == 'true' && '-DskipTests') || '' }}
